#!/bin/sh
MINTMIND_GIT_ASKPASS_PIPE=`mktemp`
TAURI_RUN_AS_NODE="1" MINTMIND_GIT_ASKPASS_PIPE="$MINTMIND_GIT_ASKPASS_PIPE" MINTMIND_GIT_ASKPASS_TYPE="https" "$MINTMIND_GIT_ASKPASS_NODE" "$MINTMIND_GIT_ASKPASS_MAIN" $MINTMIND_GIT_ASKPASS_EXTRA_ARGS $*
cat $MINTMIND_GIT_ASKPASS_PIPE
rm $MINTMIND_GIT_ASKPASS_PIPE
